// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicForm: typeof import('./components/sys/BasicForm/src/BasicForm.vue')['default']
    BasicSearch: typeof import('./components/sys/BasicSearch/src/BasicSearch.vue')['default']
    BasicTable: typeof import('./components/sys/BasicTable/src/BasicTable.vue')['default']
    BasicTree: typeof import('./components/sys/BasicTree/src/BasicTree.vue')['default']
    DragVerify: typeof import('./components/sys/Verify/src/DragVerify.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTag: typeof import('element-plus/es')['ElTag']
    Icon: typeof import('./components/sys/Icon/src/Icon.vue')['default']
    IconPicker: typeof import('./components/sys/IconPicker/src/IconPicker.vue')['default']
    ImgControl: typeof import('./components/sys/QuillEditor/components/imgControl.vue')['default']
    Modal: typeof import('./components/Modal/src/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./components/sys/QuillEditor/src/index.vue')['default']
    StaticFile: typeof import('./components/sys/StaticFile.vue')['default']
    SvgIcon: typeof import('./components/sys/SvgIcon.vue')['default']
    SysBreadcrumbs: typeof import('./components/sys/Breadcrumbs/src/SysBreadcrumbs.vue')['default']
    SysMenu: typeof import('./components/sys/Menu/src/SysMenu.vue')['default']
    SysMenuItem: typeof import('./components/sys/Menu/src/SysMenuItem.vue')['default']
    SysSubMenu: typeof import('./components/sys/Menu/src/SysSubMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
